dist: xenial
language: go
go:
- 1.12.x
sudo: required
go_import_path: github.com/allegro/consul-registration-hook
env:
- CHANGE_MINIKUBE_NONE_USER=true
before_script:
- scripts/install_local_k8s.sh
script:
- make
- make integration-test
after_success:
- bash <(curl -s https://codecov.io/bash)
before_deploy:
- make package
deploy:
  provider: releases
  api_key:
    secure: A3YddOYOSUhUBUaZrtKsXHn+Q8pRZGpbMDZBrOYaULLtwZjHBbFCVLPWRb2sio7C1+LLDYYbkdhbxPuEIManDtAnNuaA7WtcY2CVW1xnnm4nJ6coy1yyZIAGgYzt1BD214JL9MDUvVNWjy5thpWHg7mEqxd7oSf7Fp2l+jEecYd8M5iV/2b+ALR0X9iMpDlirOwQvdMHSM16ZO2RrZrBdjVRffOhe53P+rKojm1qaCXdyuxfKdcU+XPc90aDs0X0anLiKkilc0EJDtp8SsJKFuLVvCAV1POcrJtFj3JK8+7xCn5yGvhEjRMDDikDaMDunRkkF/ZCjiA8jkKJ2bs2aznJFE/qNdSe+L+iqReKCSzOxg1S4l0i680ZiOsgJS0crNoG1V4NUhmt7zxd/YdlVm0wwqss20EFCFNw43XTRd6YJ7SaQtFfZBWX0AAig6rYjzsWng6nldkkYM5i/nb+IoEmbMumdsDKWZAxNVcXAchXkMDOcmyogdd0dhRuKJ+LMRGwAm3daX/OllrL0HNSegjMnxU+tes8oswNYyRr47KIn1wvnUJorftN/k1IqUogzVwBvt3YrnOxda3U7VkpBC9PtcDDGiU9xzNu5wbfyy78mwjYJz+m5n/sMn5ct9pE6cK/AAQDfUV4tMWzhRfAuSBbFwNm+PikQ4jhJcuBfJc=
  file_glob: true
  file: build/*.tar.gz
  skip_cleanup: true
  on:
    tags: true
