name: golangci
on:
  push:
    tags:
      - v[0-9]+.*
    branches:
      - master
  pull_request:
jobs:
  golangci:
    name: lint test build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14.x
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.30
          args: --config=golangcilinter.yaml
      - name: Build and test project
        run: make test
