name: integration
on:
  workflow_dispatch:
jobs:
  golangci:
    name: lint test build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14.x
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: build project
        run: make build
      - name: install minikube
        run: scripts/install_local_k8s.sh
        env:
          CHANGE_MINIKUBE_NONE_USER: true
      - name: integration test
        run: make integration-test
        env:
          CHANGE_MINIKUBE_NONE_USER: true
