name: integration
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  golangci:
    name: lint test build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14.x
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: build project
        run: make build
      - uses: azure/setup-kubectl@v1
      - name: integration test
        run: make integration-test
        env:
          CHANGE_MINIKUBE_NONE_USER: true
