name: release
on:
  push:
    tags:
      - v[0-9].[0-9]+.[0-9]+
jobs:
  release:
    name: build release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14.x
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: build
        run: make package
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/*.tar.gz"
          token: ${{ secrets.GITHUB_TOKEN }}
